[build]
  functions = "functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["sqlite3", "bcrypt", "pg", "jsonwebtoken"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[dev]
  functions = "functions"
  publish = "public"
  port = 8000
  targetPort = 5000
